### PR TITLE
Add support for proxy as prometheus remote storage

### PR DESCRIPTION
**Pull request by mdubbyap**

### CODE REVIEW

**Comment by mdubbyap** [comment]
I need to migrate this project to govendor before this will work... stand by for a prequel to this pr

**Comment by salekseev** [comment]
I have actually tested this branch with some sample prometheus metrics and it seems to work fine at small workloads at least.

A  thing to note:
Default URL to write metrics is set to be /receive which differs from the default of /write in prometheus docs at https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/README.md. It probably makes sense to change that to match.

**Comment by salekseev** [comment]
I have actually tested this branch with some sample prometheus metrics and it seems to work fine at small workloads at least.

A  thing to note:
Default URL to write metrics is set to be /receive which differs from the default of /write in prometheus docs at https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/README.md. It probably makes sense to change that to match.

**Comment by salekseev** [comment]
I have actually tested this branch with some sample prometheus metrics and it seems to work fine at small workloads at least.

A  thing to note:
Default URL to write metrics is set to be /receive which differs from the default of /write in prometheus docs at https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/README.md. It probably makes sense to change that to match.

**Comment by salekseev** [comment]
I have actually tested this branch with some sample prometheus metrics and it seems to work fine at small workloads at least.

A  thing to note:
Default URL to write metrics is set to be /receive which differs from the default of /write in prometheus docs at https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/README.md. It probably makes sense to change that to match.

**Comment by salekseev** [comment]
I have actually tested this branch with some sample prometheus metrics and it seems to work fine at small workloads at least.

A  thing to note:
Default URL to write metrics is set to be /receive which differs from the default of /write in prometheus docs at https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/README.md. It probably makes sense to change that to match.

**Comment by mdubbyap** [comment]
@salekseev i was following the example you posted in your issue that pointed it at /receive https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/example_write_adapter is /write the more widely used? i'm not super familiar with prometheus.

**Comment by salekseev** [comment]
Yes, Prometheus examples for remote storage adapters all use /write for remote write (https://github.com/prometheus/prometheus/blob/master/documentation/examples/remote_storage/remote_storage_adapter/main.go#L205) and /read for remote read optionally.

**Comment by mdubbyap** [comment]
@salekseev cool, i've made that the default but you can configure it with ListenPath in the config file. Please take a look and let me know what you think.

**Pull request merged**
