### PR TITLE
Update format of README

### PR DESCRIPTION
**Pull request by azimman**
@cep21 All of your information is still here, just reorganized it a bit.

### CODE REVIEW

**Comment by cep21** [comment]
Can you try installing mdl and running it on the README?

```
+ mdl --warnings
(stdin):16: MD001 Header levels should only increment by one level at a time
(stdin):64: MD012 Multiple consecutive blank lines
(stdin):87: MD012 Multiple consecutive blank lines
(stdin):4: MD013 Line length
(stdin):7: MD013 Line length
(stdin):18: MD013 Line length
(stdin):67: MD013 Line length
(stdin):78: MD013 Line length
(stdin):708: MD013 Line length
(stdin):1: MD022 Headers should be surrounded by blank lines
(stdin):7: MD025 Multiple top level headers in the same document
(stdin):694: MD026 Trailing punctuation in header

(stdin):698: MD031 Fenced code blocks should be surrounded by blank lines ./circle.sh test > >(tee $CIRCLE_ARTIFACTS/test.stdout.txt) 2> >(tee $CIRCLE_ARTIFACTS/test.stderr.txt >&2) returned exit code 1
```

**Comment by azimman** [comment]
@cep21 I'll take a look... I'll ping you once it passes ci tests.

**Comment by barbara-sfx** [comment]
Noob here. I see a couple typos. Like the first sentence isn't a complete sentence. What's the process for either reporting or fixing them?

**Comment by cep21** [comment]
Go ahead and report errors (raise an issue on github with details and I'll fix them), or do a pull request with them fixed.  Either is fine.

**Pull request closed without merging**
