### PR TITLE
Migration to CircleCI 2

### PR DESCRIPTION
**Pull request by aeuio**

### CODE REVIEW

**Comment by aeuio** [comment]
last i heard someone was supposed to convert this to circleci2 - but, if you've moved to travis, that's great!  i'll close this out then.  just let me know.

**Comment by mpetazzoni** [comment]
I've done no such thing. I was talking more generally, that as a company we were moving away from Circle and use TravisCI instead (since we already have most of our public stuff building through there - client libraries, etc).

**Comment by aeuio** [comment]
thanks!  apologies, when i said "you" i meant like a group you (the metricproxy group of developers - probably should have said y'all).  i think transferring this all to travis is definitely something to consider, since most of our public stuff is building there (and travis ended up validating all my changes in this branch as well as circle, and faster!)  we'll have to wait for @mdubbyap's word on this too, i think.

**Comment by mdubbyap** [comment]
I don't care where this lands, jack had the docker image being built in circle. As long as something builds the docker image and pushes it to quay, i'm fine with it.

**Pull request merged**
