### PR TITLE
Fix typo (lxd-stable -> lxc-stable)

### PR DESCRIPTION
**Pull request by reversefold**
This change is [Reviewable](https://reviewable.io/reviews/signalfx/metricproxy/95)

### CODE REVIEW

**Comment by harnitsignalfx** [comment]
lxd-stable has deprecated and lxc-stable is not a reasonable workaround. The newer versions of go can be installed via these steps - 

sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go

I'll modify the steps in the documentation.

**Comment by harnitsignalfx** [comment]
These steps will work for 14.04 , 16.04 and 17.10 ->

sudo add-apt-repository ppa:gophers/archive
sudo apt-get update

sudo apt-get install golang-1.10

(If /usr/bin/go does not exist)
sudo ln /usr/lib/go-1.10/bin/go /usr/bin/go
OR
(If /usr/bin/go does already exist)
sudo cp /usr/lib/go-1.10/bin/go /usr/bin/go

**Comment by harnitsignalfx** [comment]
new PR -> https://github.com/signalfx/metricproxy/pull/96

**Comment by mdubbyap** [comment]
Closing in favor of https://github.com/signalfx/metricproxy/pull/97

**Pull request closed without merging**
